services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocktails
    ports:
      - 5432:5432

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # basically useless and even malicious in prod, so not adding in k8s
    env_file:
      - .env
    environment: # same values as in .env file so don't really do anything
      - PG_HOST=postgres
      - DB_HOST=postgres
#    volumes: for production so image's data is not subsituted by local
#      - ./:/app
    command: node ./bin/server.js
volumes:
  postgres_volume:

