apiVersion: v1
kind: ConfigMap
metadata:
  name: cocktails-app-configmap
data:
  DB_DATABASE: cocktails
  DB_HOST: database-1.creiqsigsuaq.eu-north-1.rds.amazonaws.com
  DB_PORT: "5432"
  LOG_LEVEL: info
  TZ: UTC
  NODE_ENV: production
  DRIVE_DISK: fs
  HOST: 0.0.0.0
  PORT: "3333"
  APP_DOMAIN: cocktails-back-solvro:3333 # NOT REAL YET
  DB_SSL: "true"